config/routes.rb
OpenProject::Application.routes.draw do
  # get 'contacts/index'

  # get 'contacts/show'

  # get 'contacts/create'

  # get 'contacts/update'

  # get 'contacts/edit'

  # get 'contacts/destroy'

  resources :partners do
    member do
      get :filter_available_members

      post :add_contact

      put :set_partner

    end

  end

  resources :contacts do
    member do
      post 'delete_partner/:partner_id', to: 'contacts#delete_partner', as: 'delete_partner'
      post :add_partner

      get :available_partners

    end 
  end

end

app/models/partner.rb
class Partner < ApplicationRecord
    has_and_belongs_to_many :items
    has_and_belongs_to_many :contacts
    self.primary_key = :partner_id
    
    scope :sorted_alphabetically, -> { order("partner_id, name") }

    def new_contact
    end

end

app/controllers/partners_controller.rb
class PartnersController < ApplicationController
  before_action :require_admin, except: [:index, :show]
  before_action :get_partner_by_identifier, except: [:index, :new, :create, :set_partner]
  before_action :get_contacts, only: [:edit, :update, :show]
  respond_to :html, :json

  helper :projects #, :custom_fields

  def index
    @partners = Partner.all.order(name: :asc)
    recode = {'partner_id'=>'id', 'name'=>'name'}
    if (request.params[:q] && request.params[:q].length > 0)
      q = request.params[:q].downcase()
      @partners = @partners.select {|e| e[:name].downcase().include?(q) || e[:partner_id].downcase().include?(q)}
    end
    respond_to do |format|
      format.html 
      format.any(:xml, :json, :js) { render request.format.to_sym => { results: { items: @partners.map {|v| {'id'=> v['partner_id'], 'name'=> v['name']} } } } }
    end

     # @custom_fields = CompanyCustomField.all.order(position: :asc)
  end

  def show
    # @projects = @company.all_projects
  end

  def new
    @partner = Partner.new
  end

  def create
    @partner = Partner.new partner_attributes

    if @partner.save
      flash[:notice] = t(:notice_successful_create)

      redirect_to @partner
    else
      render action: 'new'
    end
  end

  def edit
  end

  def update
    if @partner.update partner_attributes
      flash[:notice] = t(:notice_successful_update)

      redirect_to @partner
    else
      render action: 'edit'
    end
  end

  def destroy
    @partner.destroy
    flash[:notice] = t(:notice_partner_deleted)

    redirect_to partners_url
  end

  def set_partner
    @project= Project.find(request.params[:id])
    if (@project)
      @project.partner_id = request.params[:project][:partner_id] == '-1' ? nil : request.params[:project][:partner_id]
      @project.save
      flash[:notice] = t(:notice_partner_set_success)
    else 
      flash[:notice] = t(:notice_partner_not_set)
    end
    redirect_back(fallback_location: '/')
  end 

  # def delete_member
  #   member = User.find(params[:member_id])
  #   @company.members.delete(member)

  #   flash[:notice] = t(:notice_company_member_deleted)

  #   redirect_to edit_company_path(id: @company.identifier)
  # end

  # def add_members
  #   member_ids = params[:member_ids]
  #   @company.member_ids += member_ids

  #   flash[:notice] = t(:notice_company_member_added)

  #   redirect_to edit_company_path(id: @company.identifier)
  # end

  # def filter_available_members
  #   @members = @company.members.sorted_alphabetically
  #   found = params[:q].blank? ? User.active : User.active.like(params[:q])
  #   @available_members = found.sorted_alphabetically.limit(100) - @members

  #   render partial: 'available_members'
  # end

  # def delete_project
  #   project = Project.find(params[:project_id])
  #   @company.projects.delete(project)

  #   flash[:notice] = t(:notice_company_project_deleted)

  #   redirect_to edit_company_path(id: @company.identifier)
  # end

  # def add_projects
  #   project_ids = params[:project_ids]
  #   @company.project_ids += project_ids

  #   flash[:notice] = t(:notice_company_project_added)

  #   redirect_to edit_company_path(id: @company.identifier)
  # end

  # def filter_available_projects
  #   @projects = @company.projects.sorted_alphabetically
  #   found = params[:q].blank? ? Project.active : Project.active.like(params[:q])
  #   @available_projects = found.sorted_alphabetically.limit(100) - @projects

  #   render partial: 'available_projects'
  # end

  # private

  # def get_settings
  #   @settings = Setting.plugin_openproject_companies
  # end

  # def get_members
  #   @members = @company.members.sorted_alphabetically
  #   @available_members = User.active.sorted_alphabetically.limit(100) - @members
  # end

  # def get_projects
  #   @projects = @company.projects.sorted_alphabetically

  #   all_projects = Project.active.sorted_alphabetically.order(name: :asc).limit(100)
  #   @available_projects = all_projects - @projects
  # end

  def get_partner_by_identifier
    @partner = Partner.find_by!(partner_id: params[:id])
  rescue ActiveRecord::RecordNotFound
    render_404
  end

  def partner_attributes
    params
      .require(:partner)
      .permit(:partner_id, :name)
  end

  def default_breadcrumb
    if action_name == 'index' || action_name == 'new'
      t('label_partner_plural')
    else
      # ActionController::Base.helpers.link_to(t('label_partner_plural'), partner_path)
    end
  end

  def show_local_breadcrumb
    true
  end

  def partners_path
  end

  def add_contact
    contact  = Contact.find(request.params[:partner][:new_contact])
    partner = Partner.find(request.params[:id])
    if (contact && partner)
      contact.partners << partner
      flash[:notice] = t(:notice_association_added)
      redirect_back(fallback_location: partners_url)
    end
  rescue => error
    puts error.inspect
    render_404
  end

  def available_contacts
    id = request.params[:id].gsub(/[^0-9a-zA-Z .,@ąčęėįšųūžAČĘĖĮŠŲŽ]/, "")
    # no SQL injection here because 
    # 1) get_partner_by_identifier is called and project by :id is found
    # 2) project_id length is very limited
    # 3) supplied parameter is sanitized
    @contacts = Contact.joins("LEFT JOIN contacts_partners ON contacts_partners.contact_id = contacts.id and contacts_partners.partner_id = '#{id}'").
      where('contacts_partners.partner_id is null and (lower(contacts.name) like :q or contacts.phone like :q or lower(contacts.email) like :q)', 
        q: "%#{request.params[:q].downcase}%").
      order(name: :asc)
    respond_to do |format|
      format.any(:json) { render request.format.to_sym => { results: { items: @contacts } } }
    end

  end

  def get_contacts
    @contacts = @partner.contacts.sorted_alphabetically
    @available_contacts = Contact.sorted_alphabetically.limit(100) - @contacts
  end
end

app/views/partners/_contacts.html.erb
<!-- div class="grid-block -no-outer-padding" -->
  <div class="grid-content medium-6 small-6">
    <% if @contacts.any? %>
      <fieldset class="form--fieldset">
        <legend class="form--fieldset-legend"><%= l(:label_associated_with_contacts) %></legend>
        <div class="generic-table--container">
          <div class="generic-table--results-container">
            <table class="generic-table list partners">
              <tbody>
                <% @contacts.each do |contact| %>
                  <% next if @partner.new_record? %>
                  <tr id="contact-<%= contact.id %>" class="contact">
                    <td class="contact -no-padding-left"><%= contact.name %></td>
                    <td class="buttons">
                      <%=
                        link_to "",
                                delete_partner_contact_path(id: contact, partner_id: @partner.partner_id),
                                method: :post,
                                title: t(:button_delete),
                                class: 'icon icon-delete'
                      %>
                    </td>
                  </tr>
                <% end; reset_cycle %>
              </tbody>
            </table>
          </div>
        </div>
      </fieldset>
    <% else %>
        <%= no_results_box custom_title: t(:notice_no_associated_contacts) %>
    <% end %>
  </div>
<% if true %>
<h4>Associate contact</h4>

<%= labelled_tabular_form_for @partner,
                              url: add_contact_partner_path(id: @partner),
                              method: :post do |form| %>
    <div class="form--field">
        <% if @partner && @partner.persisted? %>
            <% partner = [t('label_none_parentheses'), -1]
                options = { :'data-ajaxURL' => url_for({action: 'available_contacts', id: @partner}),
                            :'data-contactId' => @partner.id,
                            :'data-selected' => [partner].to_json
                        }
            %>
            <%= javascript_include_tag "autocompleter.js" %>
            <%= javascript_include_tag "partner/contact_attribute.js" %>
            <%= form.select(:new_contact, options_for_select([]), {container_class: '-wide'}, options) %>
        <% end %>
    </div>
    <%= form.button l(:button_add), class: 'button -highlight -with-icon icon-checkmark' %>
<% end %>
<% end %>
<!-- /div -->

app/views/partners/_form.html.erb
<%= error_messages_for 'partner' %>

<%= form_for @partner, :builder => TabularFormBuilder, :html => {:multipart => true} do |f| %>

  <section class="form--section">
    <div class="form--field -required"><%= f.text_field :partner_id, :required => true, container_class: '-wide' %></div>
    <div class="form--field -required"><%= f.text_field :name, :required => true, container_class: '-wide' %></div>


  </section>

  <%= styled_button_tag l(@partner.new_record? ? :button_create : :button_save), class: '-highlight -with-icon icon-checkmark' %>

<% end %>

<% unless @partner.new_record? %>

  <div style="clear: both;"></div>

  <div id="partner-contacts">
    <%= render :partial => 'contacts' %>
  </div>

<% end %>

app/views/partners/edit.html.erb
<% breadcrumb_paths(default_breadcrumb, @partner.partner_id) %>
<%= toolbar title: @partner.name %>

<%= render :partial => 'form' %>

<% html_title "#{t(:label_partner_plural)} - #{@partner.name}" %>

app/views/partners/index.html.erb
<% html_title t(:label_partner_plural) -%>
<% breadcrumb_paths(link_to(l(:label_administration), controller: '/admin'), link_to(l(:label_partner_plural), controller: '/partners')) %>

<%= toolbar title: t(:label_partner_plural) do %>
  <% if User.current.allowed_to?(:add_partner, nil, :global => true) %>
    <li class="toolbar-item">
      <%= link_to new_partner_path, :class => 'button -alt-highlight' do %>
        <%= op_icon('button--icon icon-add') %>
        <span class="button--text"><%= t(:label_partner)  %></span>
      <% end %>
    </li>
  <% end %>
  <%= call_hook(:partner_admin_action_menu) %>
<% end %>

<div class="generic-table--container">
  <div class="generic-table--results-container">
    <table class="generic-table">
      <colgroup>
        <% (1..3).each do |_| %>
          <col highlight-col>
        <% end %>
      </colgroup>
      <thead>
        <tr>
          <th>
            <div class="generic-table--header-outer">
              <div class="generic-table--header">
                <%= Partner.human_attribute_name :partner_id %>
              </div>
            </div>
          </th>
          <th>
            <div class="generic-table--header-outer">
              <div class="generic-table--header">
                <%= Partner.human_attribute_name :name %>
              </div>
            </div>
          </th>



          <% if User.current.allowed_to?(:edit_partner, nil, :global => true) %>
            <th>
              <div class="generic-table--empty-header"></div>
            </th>
          <% end %>
        </tr>
      </thead>
      <tbody>
        <% @partners.each do |partner| %>
          <tr class="<%= cycle("odd", "even") %>">
            <td class="name center"><%= link_to partner.partner_id, partner %></td>
            <td><%= partner.name %></td>
            <% if User.current.allowed_to?(:edit_partner, nil, :global => true) %>
              <td class="buttons">
                <%= link_to "", edit_partner_path(partner), class: 'icon icon-edit' %>
                <%=
                  link_to(
                    "",
                    partner,
                    method: :delete,
                    class: 'icon icon-delete',
                    data: { confirm: t(:text_are_you_sure) }
                  )
                %>
              </td>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/partners/new.html.erb
<% breadcrumb_paths(default_breadcrumb, t(:label_partner_new)) %>
<%= toolbar title: t(:label_partner_new) %>

<%= render :partial => 'form' %>

<% html_title t(:label_partner_new) %>

app/views/partners/show.html.erb
<% html_title "#{t(:label_partner)} - #{@partner.name}" %>
<% breadcrumb_paths(link_to(l(:label_administration), controller: '/admin'), link_to(l(:label_partner_plural), controller: '/partners'), @partner.name) %>

<%= toolbar title: @partner.name do %>
  <% if User.current.allowed_to?(:edit_partner, nil, :global => true) %>
    <li class="toolbar-item">
      <%= link_to edit_partner_path(@partner), :class => 'button' do %>
        <%= op_icon('button--icon icon-edit') %>
        <span class="button--text"><%= t(:label_edit) %></span>
      <% end %>
    </li>
  <% end %>
  <% if User.current.allowed_to?(:add_partner, nil, :global => true) %>
    <li class="toolbar-item">
      <%= link_to new_partner_path, :class => 'button -alt-highlight' do %>
        <%= op_icon('button--icon icon-add') %>
        <span class="button--text"><%= t(:label_partner)  %></span>
      <% end %>
    </li>
  <% end %>
<% end %>

<h3><%= @partner.name %></h3>

<div class="grid-block -no-outer-padding">


</div>

<% content_for :header_tags do %>
  <%= stylesheet_link_tag 'partner/partner', plugin: 'openproject_partner' %>
<% end %>