config/routes.rb
OpenProject::Application.routes.draw do
  # get 'contacts/index'

  # get 'contacts/show'

  # get 'contacts/create'

  # get 'contacts/update'

  # get 'contacts/edit'

  # get 'contacts/destroy'

  resources :partners do
    member do
      get :filter_available_members

      post :add_contact

      put :set_partner

    end

  end

  resources :contacts do
    member do
      post 'delete_partner/:partner_id', to: 'contacts#delete_partner', as: 'delete_partner'
      post :add_partner

      get :available_partners

    end 
  end

end

app/models/contact.rb
class Contact < ApplicationRecord
    has_and_belongs_to_many :partners

    scope :sorted_alphabetically, -> { order("name, phone, email") }

    def new_partner
    end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :require_admin, except: [:index, :show]
  before_action :get_contact_by_identifier, except: [:index, :new, :create]
  before_action :get_partners, only: [:edit, :update, :show]

  helper :projects #, :custom_fields

  def index
    @contacts = Contact.includes(:partners).all.order(name: :asc)
    if (request.params[:q] && request.params[:q].length > 0)
      q = request.params[:q].downcase()
      @contacts = @contacts.select {|e| e[:name].downcase().include?(q) || e[:email].downcase().include?(q) || e[:phone].downcase().include?(q)}
    end
    respond_to do |format|
      format.html 
      format.any(:xml, :json, :js) { render request.format.to_sym => { results: { items: @contacts } } }
    end
  end

  def new
    @contact = Contact.new
  end

  def show
  end

  def create
    @contact = Contact.new contact_attributes

    if @contact.save
      flash[:notice] = t(:notice_successful_create)

      redirect_to @contact
    else
      render action: 'new'
    end
  end


  def update
    if @contact.update contact_attributes
      flash[:notice] = t(:notice_successful_update)

      redirect_to @contact
    else
      render action: 'edit'
    end
  end


  def edit
  end

  def destroy
    @contact.destroy
    flash[:notice] = t(:notice_contact_deleted)

    redirect_to contacts_url
  end

  def contact_attributes
    params
      .require(:contact)
      .permit(:name, :phone, :email)
  end  

  def add_partner
    contact  = Contact.find(request.params[:id])
    partner = Partner.find(request.params[:contact][:new_partner])
    if (contact && partner)
      contact.partners << partner
      flash[:notice] = t(:notice_association_added)
      redirect_back(fallback_location: contacts_url)
    end
  rescue => error
    puts error.inspect
    render_404
  end

  def delete_partner
    contact  = Contact.find(request.params[:id])
    partner = contact.partners.find(request.params[:partner_id])

    if (contact && partner)
      contact.partners.delete(partner)
      flash[:notice] = t(:notice_association_removed)
      redirect_back(fallback_location: contacts_url)
    end 
  rescue => error
    puts error.inspect
    render_404
  end 

  def available_partners
    @partners = Partner.joins("LEFT JOIN contacts_partners ON contacts_partners.partner_id = partners.partner_id and contacts_partners.contact_id = #{Integer(request.params[:id])}").
      where('contacts_partners.contact_id is null and (lower(partners.partner_id) like :q or lower(partners.name) like :q)', 
        q: "%#{request.params[:q].downcase}%").
      order(name: :asc)
    respond_to do |format|
      format.any(:json) { render request.format.to_sym => { results: { items: @partners.map {|v| {'id'=> v['partner_id'], 'name'=> v['name']} } } } }
    end

  end

  private

  def get_contact_by_identifier
    @contact = Contact.find_by!(id: params[:id])
  rescue ActiveRecord::RecordNotFound
    render_404
  end

  def get_partners
    @partners = @contact.partners.sorted_alphabetically
    @available_partners = Partner.sorted_alphabetically.limit(100) - @partners
  end

end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/_available_partners.html.erb
<%= companies_check_box_tags('partner_ids[]', @available_partners) %>

app/views/contacts/_form.html.erb
<%= error_messages_for 'contact' %>

<%= form_for @contact, :builder => TabularFormBuilder, :html => {:multipart => true} do |f| %>

  <section class="form--section">
    <div class="form--field -required"><%= f.text_field :name, :required => true, container_class: '-wide' %></div>
    <div class="form--field"><%= f.text_field :phone, container_class: '-wide' %></div>
    <div class="form--field"><%= f.text_field :email, container_class: '-wide' %></div>


  </section>

  <%= styled_button_tag l(@contact.new_record? ? :button_create : :button_save), class: '-highlight -with-icon icon-checkmark' %>

<% end %>

<% unless @contact.new_record? %>

  <div style="clear: both;"></div>

  <div id="company-projects">
    <%= render :partial => 'partners' %>
  </div>

<% end %>

app/views/contacts/_partners.html.erb
<!-- div class="grid-block -no-outer-padding" -->
  <div class="grid-content medium-6 small-6">
    <% if @partners.any? %>
      <fieldset class="form--fieldset">
        <legend class="form--fieldset-legend"><%= l(:label_associated_with_partners) %></legend>
        <div class="generic-table--container">
          <div class="generic-table--results-container">
            <table class="generic-table list partners">
              <tbody>
                <% @partners.each do |partner| %>
                  <% next if partner.new_record? %>
                  <tr id="partner-<%= partner.partner_id %>" class="partner">
                    <td class="partner -no-padding-left"><%= partner.name %></td>
                    <td class="buttons">
                      <%=
                        link_to "",
                                delete_partner_contact_path(id: @contact, partner_id: partner.partner_id),
                                method: :post,
                                title: t(:button_delete),
                                class: 'icon icon-delete'
                      %>
                    </td>
                  </tr>
                <% end; reset_cycle %>
              </tbody>
            </table>
          </div>
        </div>
      </fieldset>
    <% else %>
        <%= no_results_box custom_title: t(:notice_no_associated_partners) %>
    <% end %>
  </div>

<h4>Associate partner</h4>

<%= labelled_tabular_form_for @contact,
                              url: add_partner_contact_path(id: @contact),
                              method: :post do |form| %>
    <div class="form--field">
        <% if @contact && @contact.persisted? %>
            <% partner = [t('label_none_parentheses'), -1]
                options = { :'data-ajaxURL' => url_for({action: 'available_partners', id: @contact}),
                            :'data-contactId' => @contact.id,
                            :'data-selected' => [partner].to_json
                        }
            %>
            <%= javascript_include_tag "autocompleter.js" %>
            <%= javascript_include_tag "contact/partner_attribute.js" %>
            <%= form.select(:new_partner, options_for_select([]), {container_class: '-wide'}, options) %>
        <% end %>
    </div>
    <%= form.button l(:button_add), class: 'button -highlight -with-icon icon-checkmark' %>
<% end %>
<!-- /div -->

app/views/contacts/edit.html.erb
<% breadcrumb_paths(default_breadcrumb, @contact.name) %>
<%= toolbar title: @contact.name %>

<%= render :partial => 'form' %>

<% html_title "#{t(:label_contact_plural)} - #{@contact.name}" %>

app/views/contacts/index.html.erb
<% html_title t(:label_contact_plural) -%>
<% breadcrumb_paths(link_to(l(:label_administration), controller: '/admin'), link_to(l(:label_contact_plural), controller: '/contacts')) %>

<%= toolbar title: t(:label_contact_plural) do %>
  <% if User.current.allowed_to?(:add_contact, nil, :global => true) %>
    <li class="toolbar-item">
      <%= link_to new_contact_path, :class => 'button -alt-highlight' do %>
        <%= op_icon('button--icon icon-add') %>
        <span class="button--text"><%= t(:label_contact)  %></span>
      <% end %>
    </li>
  <% end %>
  <%= call_hook(:contact_admin_action_menu) %>
<% end %>

<div class="generic-table--container">
  <div class="generic-table--results-container">
    <table class="generic-table">
      <colgroup>
        <% (1..4).each do |_| %>
          <col highlight-col>
        <% end %>
      </colgroup>
      <thead>
        <tr>
          <th>
            <div class="generic-table--header-outer">
              <div class="generic-table--header">
                <%= Contact.human_attribute_name :name %>
              </div>
            </div>
          </th>
          <th>
            <div class="generic-table--header-outer">
              <div class="generic-table--header">
                <%= Contact.human_attribute_name :phone %>
              </div>
            </div>
          </th>
          <th>
            <div class="generic-table--header-outer">
              <div class="generic-table--header">
                <%= Contact.human_attribute_name :email %>
              </div>
            </div>
          </th>
          <th>
            <div class="generic-table--header-outer">
              <div class="generic-table--header">
                <%= Contact.human_attribute_name :partner %>
              </div>
            </div>
          </th>



          <% if User.current.allowed_to?(:edit_contact, nil, :global => true) %>
            <th>
              <div class="generic-table--empty-header"></div>
            </th>
          <% end %>
        </tr>
      </thead>
      <tbody>
        <% @contacts.each do |contact| %>
          <tr class="<%= cycle("odd", "even") %>">
            <td class="name center"><%= link_to contact.name, contact %></td>
            <td><%= contact.phone %></td>
            <td><%= contact.email %></td>
            <td><%= contact.partner_ids.count > 0 ? contact.partner_ids.join(',') : '-' %></td>
            <% if User.current.allowed_to?(:edit_contact, nil, :global => true) %>
              <td class="buttons">
                <%= link_to "", edit_contact_path(contact), class: 'icon icon-edit' %>
                <%=
                  link_to(
                    "",
                    contact,
                    method: :delete,
                    class: 'icon icon-delete',
                    data: { confirm: t(:text_are_you_sure) }
                  )
                %>
              </td>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/contacts/new.html.erb
<% breadcrumb_paths(default_breadcrumb, t(:label_contact_new)) %>
<%= toolbar title: t(:label_contact_new) %>

<%= render :partial => 'form' %>

<% html_title t(:label_contact_new) %>

app/views/contacts/show.html.erb
<% html_title "#{t(:label_contact)} - #{@contact.name}" %>
<% breadcrumb_paths(link_to(l(:label_administration), controller: '/admin'), link_to(l(:label_contact_plural), controller: '/contacts'), @contact.name) %>

<%= toolbar title: @contact.name do %>
  <% if User.current.allowed_to?(:edit_contact, nil, :global => true) %>
    <li class="toolbar-item">
      <%= link_to edit_contact_path(@contact), :class => 'button' do %>
        <%= op_icon('button--icon icon-edit') %>
        <span class="button--text"><%= t(:label_edit) %></span>
      <% end %>
    </li>
  <% end %>
  <% if User.current.allowed_to?(:add_contact, nil, :global => true) %>
    <li class="toolbar-item">
      <%= link_to new_contact_path, :class => 'button -alt-highlight' do %>
        <%= op_icon('button--icon icon-add') %>
        <span class="button--text"><%= t(:label_contact)  %></span>
      <% end %>
    </li>
  <% end %>
<% end %>

<h3><%= @contact.name %></h3>

<div class="grid-block -no-outer-padding">
  <div class="form--field">
      <label class="form--label">
        <b><%= t(:label_phone) %></b>
      </label>
      <span class="form--field-container">
        <% if @contact.phone %>
          <a href="tel:<%= @contact.phone %>"><%= @contact.phone %></a>
        <% end %>
      </span>
  </div>
  <div class="form--field">
      <label class="form--label">
        <b><%= t(:label_email) %></b>
      </label>
      <span class="form--field-container">
        <% if @contact.email %>
          <a href="mailto:<%= @contact.email %>"><%= @contact.email %></a>
        <% end %>
      </span>
  </div>

</div>